on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/workflow_dispatch@v2
        with:
          workflow_file: .github/workflows/basic_workflow.yml